version: '3.4'

services:
  db:
    image: caiozed/custom-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "America/Sao_Paulo"
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: aspnetcoreapiexample
    ports:
      - "3308:3306"
    networks:
      - examplenetwork
      
  aspnetcoreapiexample:
    image: caiozed/aspnetcoreapiexample
    build:
      context: .
      dockerfile: AspNetCoreApiExample/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44302
    ports:
      - "6000:80"
      - "44302:443"
    networks:
      - examplenetwork
    links:
      - db
    depends_on:
      - db
networks: 
  examplenetwork:
    driver: bridge